title: Скучное место
description: Hacker Space Boring Place.
show_downloads: true

baseurl: ""
url: "http://boringplace.org"
google_analytics:
host: tor

theme: jekyll-theme-hacker
lang: ru
langs:
  - ru
  - en

twitter_username: boringplacenet
github_username: boringplace

plugins:
  - jekyll-seo-tag

# Exclude files from being included into resulting website
exclude:
  - makefile
  - README.md
  - thumbnail.png

